/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MainWindow */

#ifndef _Included_MainWindow
#define _Included_MainWindow
#ifdef __cplusplus
extern "C" {
#endif
#undef MainWindow_FOCUS_TRAVERSABLE_UNKNOWN
#define MainWindow_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef MainWindow_FOCUS_TRAVERSABLE_DEFAULT
#define MainWindow_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef MainWindow_FOCUS_TRAVERSABLE_SET
#define MainWindow_FOCUS_TRAVERSABLE_SET 2L
/* Inaccessible static: focusTraversalKeyPropertyNames */
/* Inaccessible static: LOCK */
/* Inaccessible static: dbg */
/* Inaccessible static: isInc */
/* Inaccessible static: incRate */
#undef MainWindow_TOP_ALIGNMENT
#define MainWindow_TOP_ALIGNMENT 0.0f
#undef MainWindow_CENTER_ALIGNMENT
#define MainWindow_CENTER_ALIGNMENT 0.5f
#undef MainWindow_BOTTOM_ALIGNMENT
#define MainWindow_BOTTOM_ALIGNMENT 1.0f
#undef MainWindow_LEFT_ALIGNMENT
#define MainWindow_LEFT_ALIGNMENT 0.0f
#undef MainWindow_RIGHT_ALIGNMENT
#define MainWindow_RIGHT_ALIGNMENT 1.0f
#undef MainWindow_serialVersionUID
#define MainWindow_serialVersionUID -7644114512714619750i64
/* Inaccessible static: metrics */
/* Inaccessible static: class_00024java_00024awt_00024Component */
/* Inaccessible static: class_00024java_00024awt_00024event_00024ComponentListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024FocusListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024HierarchyListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024HierarchyBoundsListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024KeyListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024MouseListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024MouseMotionListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024MouseWheelListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024InputMethodListener */
/* Inaccessible static: class_00024java_00024beans_00024PropertyChangeListener */
#undef MainWindow_serialVersionUID
#define MainWindow_serialVersionUID 4613797578919906343i64
/* Inaccessible static: dbg */
#undef MainWindow_INCLUDE_SELF
#define MainWindow_INCLUDE_SELF 1L
#undef MainWindow_SEARCH_HEAVYWEIGHTS
#define MainWindow_SEARCH_HEAVYWEIGHTS 1L
/* Inaccessible static: class_00024java_00024awt_00024Container */
/* Inaccessible static: class_00024java_00024awt_00024event_00024ContainerListener */
/* Inaccessible static: systemSyncLWRequests */
#undef MainWindow_OPENED
#define MainWindow_OPENED 1L
/* Inaccessible static: nameCounter */
#undef MainWindow_serialVersionUID
#define MainWindow_serialVersionUID 4497834738069338734i64
/* Inaccessible static: dbg */
/* Inaccessible static: class_00024java_00024awt_00024Window */
/* Inaccessible static: class_00024java_00024awt_00024event_00024WindowListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024WindowFocusListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024WindowStateListener */
#undef MainWindow_DEFAULT_CURSOR
#define MainWindow_DEFAULT_CURSOR 0L
#undef MainWindow_CROSSHAIR_CURSOR
#define MainWindow_CROSSHAIR_CURSOR 1L
#undef MainWindow_TEXT_CURSOR
#define MainWindow_TEXT_CURSOR 2L
#undef MainWindow_WAIT_CURSOR
#define MainWindow_WAIT_CURSOR 3L
#undef MainWindow_SW_RESIZE_CURSOR
#define MainWindow_SW_RESIZE_CURSOR 4L
#undef MainWindow_SE_RESIZE_CURSOR
#define MainWindow_SE_RESIZE_CURSOR 5L
#undef MainWindow_NW_RESIZE_CURSOR
#define MainWindow_NW_RESIZE_CURSOR 6L
#undef MainWindow_NE_RESIZE_CURSOR
#define MainWindow_NE_RESIZE_CURSOR 7L
#undef MainWindow_N_RESIZE_CURSOR
#define MainWindow_N_RESIZE_CURSOR 8L
#undef MainWindow_S_RESIZE_CURSOR
#define MainWindow_S_RESIZE_CURSOR 9L
#undef MainWindow_W_RESIZE_CURSOR
#define MainWindow_W_RESIZE_CURSOR 10L
#undef MainWindow_E_RESIZE_CURSOR
#define MainWindow_E_RESIZE_CURSOR 11L
#undef MainWindow_HAND_CURSOR
#define MainWindow_HAND_CURSOR 12L
#undef MainWindow_MOVE_CURSOR
#define MainWindow_MOVE_CURSOR 13L
#undef MainWindow_NORMAL
#define MainWindow_NORMAL 0L
#undef MainWindow_ICONIFIED
#define MainWindow_ICONIFIED 1L
#undef MainWindow_MAXIMIZED_HORIZ
#define MainWindow_MAXIMIZED_HORIZ 2L
#undef MainWindow_MAXIMIZED_VERT
#define MainWindow_MAXIMIZED_VERT 4L
#undef MainWindow_MAXIMIZED_BOTH
#define MainWindow_MAXIMIZED_BOTH 6L
/* Inaccessible static: nameCounter */
#undef MainWindow_serialVersionUID
#define MainWindow_serialVersionUID 2673458971256075116i64
/* Inaccessible static: class_00024java_00024awt_00024Frame */
#undef MainWindow_EXIT_ON_CLOSE
#define MainWindow_EXIT_ON_CLOSE 3L
/* Inaccessible static: defaultLookAndFeelDecoratedKey */
/*
 * Class:     MainWindow
 * Method:    mf2t
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_MainWindow_mf2t
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     MainWindow
 * Method:    t2n
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_MainWindow_t2n
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     MainWindow
 * Method:    fsplit
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_MainWindow_fsplit
  (JNIEnv *, jobject, jstring, jstring, jstring, jboolean);

/*
 * Class:     MainWindow
 * Method:    bp
 * Signature: (ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_MainWindow_bp
  (JNIEnv *, jobject, jint, jstring, jstring, jstring, jstring, jstring, jstring);

/*
 * Class:     MainWindow
 * Method:    cross
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_MainWindow_cross
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     MainWindow
 * Method:    nn2t
 * Signature: (ILjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_MainWindow_nn2t
  (JNIEnv *, jobject, jint, jstring, jstring);

/*
 * Class:     MainWindow
 * Method:    t2mf
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_MainWindow_t2mf
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
